### ISSUE TITLE
katalóg požiadaviek - nezrovnalosť

### ISSUE THREAD

**Issue by kubis-svorc** [TIS2019-FMFI/meranie-velicin#1]
v 3.2.2 je spomínané rolovacie menu ktoré sa po kliknutí zobrazí ale v 3.2.1 je že nebude používať myš. Takže ako to má byť?

**Comment by keszeghova** [comment]
nezrovnalost bola upravena v katalogu poziadaviek

**Comment by pavelpetrovic** [comment]
nemáte tu issues, na ostatné úlohy.
kartičky, ktoré vytvárate v projekte nech sú vždy issues.

prečítal som si Váš KP, keďže nemáte na KP issue !! tak spätnú väzbu uvádzam tu (napravte to a prelinkujte toto tam)

• nainštalovaný Microsoft Office Excel
  - naozaj je potrebný, alebo to bude fungovať aj napr. s LibreOffice?

3.1.2. Voľba meranej veličiny
 - zistiť, či táto informácia nie je dostupná automaticky z manuálneho ovládania na prístroji, resp. či sa dá prestavovať sw

3.1.3. Nastaviteľná perióda merania
 - chýbajú mi mantinely - od koľko do koľko, príp. s akým krokom

3.1.5. Tvorba tabuľky
 - dá sa v nej scrollovať? dá sa v nej scrollovať aj počas merania alebo až po zastavení merania?

je možné meranie "odštartovať" a "zastaviť"?

3.1.6. Export tabuľky
  "exportovať vytvorenú tabuľku do Excelu." - čo sa tým myslí? v akom výstupnom formáte to bude? .xls alebo .csv?
  hneď to otvorí excel, alebo si to musí z excelu importovať?

3.1.7. Tvorba grafu
  - aj priebežne, alebo len po zastavení merania?
  - je možné v grafe scrollovať do histórie?
  - má graf zafixované rozmery? (dá sa aj okno aplikácie natiahnuť, aby bolo vidieť viac?)
  - je graf viditeľný vždy, alebo iba keď si ho "zapne"?

3.1.8. Uloženie nameraných hodnôt
  - líši sa to nejak od bodu 3.1.6?
  - ak áno, čo to znamená "na neskôr"?

3.1.9. Načítanie uložených meraní – domáce úlohy
  - toto treba upresniť ako sa to celé myslí?
  
3.3.1. Žiadna myš – len klávesnica
  -  nemohlo by to fungovať "obojako" aj myš aj klávesové skratky (potom by bol sw použiteľný pre všetkých)

chýba mi tam informácia o tom, ako bude sw reagovať na rozličné rozlíšenia obrazovky, či sa dá spustiť 
v maximalizovanom režime a či tomu prispôsobí aj veľkosť písma a ovládacích prvkov (podľa mňa by mal)

ešte by sa mi páčilo, keby softvér svoj výstupný (a exportovaný?) súbor nazval podľa dátumu a presného času (v ms), keď bolo
meranie začaté - jednak pre prehľadnosť súborov v priečinku a jednak pre prípadnú synchronizáciu s iným meraním,

ak by boli pripojené dva prístroje

to mi zároveň pripomína tému konfigurácie - zrovna to, čo v tom predchádzajúcom sw nefungovalo - aby bolo
možné určiť z ktorého portu (comX) bude program čítať

toto nastavenie si program zapamätá a druhý raz ho netreba zadávať, ak sa prístroj pripojí do rovnakého portu

v prípade, že nastavenie nie je možné uložiť (priečinok je read-only), uloženie konfigurácie sa nevykoná, 
ale inak bude program pracovať správne

pridajte, prosím, že aplikácia je spustiteľná aj viackrát naraz na tom istom počítači (pre prípadné viaceré zariadenia)

ešte aj toto: program sa dá odštartovať priamo z "Prieskumníka" jedným dvojklikom (ENTEROM)
(aby napr. nebolo treba písať niečo do príkazového riadku)

mohli by ste tam, prosím, prosím, pridať ešte aj toto?

 - softvér bude pripravený aj na pripojenie špecializovaného zariadenia, ktoré dodá cvičiaci, na čítanie grafov 
   pomocou zvukového signálu? 
     (s tým, že táto požiadavka sa označí ako doplnková (nejakým symbolom) s vysvetlením, že bude 
      naprogramovaná, iba ak bude zariadenie k dispozícii)
     predpoklad je, že zariadenie bude vysielať na sériový port jedno číslo 0-1023, ktoré zodpovedá pozícii na
     x-ovej osi a aplikácia bude vydávať zvuk príslušnej výšky podľa hodnoty v grafe na danej x-ovej pozícii.
   softvér by toto mohol toto externé posuvné zariadenie nahradiť aj obyčajnými šípkami vľavo-vpravo na klávesnici
   ak zariadenie nie je k dispozícii (celkom na kraji vľavo a vpravo sa zvuk vypne - tým pádom sa vie navigovať,
   inou klávesou prepína zrnitosť, po ktorej sa na x-ovej osi pohybuje - tá sa zobrazuje tak, aby mu to čítačka
   z obrazovky prečítala)

**Comment by pavelpetrovic** [comment]
a ešte: nech sa prvá stať nevolá "úvodné slovo" ale "Účel katalógu požiadaviek" a nech to tam je zrozumiteľne vysvetlené. vďaka.
