### ISSUE TITLE
prepis stretnutia so zadávateľom

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#10]
upraviť text podľa pripomienok zadávateľa

**Comment by kubis-svorc** [comment]
Nerozumiem presne "ktoré čo najviac zjednodušili žiakom ovládanie." aby sa zmenilo na zjednoduší. Taká veta tam ani nie je, keď si dám vyhľadať hentakú frázu v katalógu.

**Comment by kubis-svorc** [comment]
Upravené
