### ISSUE TITLE
Focus na tabulku

### ISSUE THREAD

**Issue by Savlar** [TIS2019-FMFI/meranie-velicin#112]
ked sa da focus na tabulku po ukonceni merania NVDA zacne citat cely grid

**Comment by Anna-Rebeka** [comment]
Povie nahlas len "grid window" a tiež len podľa toho, ako má používateľ nastavené NVDA. Mne to napríklad neprečíta vôbec.
Toto sa teda nedá rozumne a bezpečne vyriešiť, lebo ak sa to aj zakáže, tak im môže čítať resp. nečítať iné prvky podľa ich preferencií. Tiež sme sa dozvedeli, že nepoužívajú len NVDA. Ale rôzne iné čítače. Teda toto by som pre 100% istotu kompatibility neprenastavovala.
