### ISSUE TITLE
KP - upravena verzia

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#17]

**Comment by pavelpetrovic** [comment]
Ďakujem za aktualizáciu KP. Viaceré moje pripomienky z #1 ste odignorovali, bez toho, aby ste to vysvetlili. Tu pridávam aktuálne. Tieto ešte treba zapracovať pred tým, ako to bude pripravené na schvaľovanie zadávateľom.

2.2. a 3.1.2. Určite iba teplota, prúd, odpor? Prečo nie aj napätie? 
3.1.3. prosím upresniť, či sú nejaké obmedzenia (min/max/krok) na tieto dve nastavenia.
3.1.4. aj keď je prístroj odpojený? Ako sa prejaví odpojenie prístroja? Program spadne?
3.1.7. čo sú to fixné rozmery? myslí sa tým škála na osi, alebo počet bodov na obrazovke? prosím upresniť.
3.1.9. pomocou iných grafických prvkov - t.j. už nie pomocou klávesnice? prosím upresniť. Inými slovami, keď v 3.3.1. je uvedené, že všetko ide klávesnicou, tak to tu netreba zdôrazňovať. Stále si ale myslím, že by bolo oveľa lepšie, ak by sa aplikácia dala ovládať AJ myšou, nielen klávesnicou.
3.1.11. odporúčam nevyjadrovať sa k polohe a veľkostiam plôch, ale len vymenovať, ktoré tam budú, toto si nechajte na návrh používateľského rozhrania. (predčasný návrh)
3.3.6. "V prípade nižšieho rozlíšenia budú ovládacie prvky vhodne naškálované." - ak toto nie je požadované zadávateľkou, tak to navrhujem vypustiť. Rozlíšenie 720 na výšku je už natoľko malé, že sa s tým asi dá žiť a nestojí to za námahu. Horšie s čitateľnosťou to bude na displeji s veľkým rozlíšením - krajšie by bolo, keby aplikácia bola naškálovaná vždy na veľkosť okna, ak už sa so škálovaním chcete zaoberať, inak to podľa mňa netreba. 
3.4.1 ešte prosím rozšírte takto: "Na x-ovej pozícii sa žiak posúva vodorovným posuvným potenciometrom. 3.4.2. V režime zobrazeného grafu funguje prezeranie grafu cez externé zariadenie automaticky, ak je pripojené, bez potreby akéhokoľvek ovládania v programe."

Ešte mám aj takéto otázky:
 - je možné prerušiť meranie, ak žiak chybne zadal príliš dlhý čas merania, alebo na to musí vypnúť celý program a znovu ho zapnúť?
 - už minule som sa pýtal, ale stále som sa nedozvedel, či sa v tabuľke bude dať nejako scrollovať, ak všetky hodnoty nevôjdu na obrazovku a to isté platí pre graf - čo v ňom bude zobrazené? Úplne celé meranie, alebo len jeho posúvateľný výsek? Ak je hodnôt veľa, bude to vôbec čitateľné, keď to bude celé nahustené na jednej kope?
 - určite sa v KP treba vyjadriť k tomu, či sa bude v aplikácii nastavovať port (ako som minule písal, mohlo by si to pamätať posledné nastavenie, aby to nemusel zadávať vždy, keď program spustí), alebo či nebodaj bude port detegovať automaticky?
Ďakujem.

**Comment by pavelpetrovic** [comment]
v 1. casti - pre koho je KP urceny.
napatie konzistetne
ostatne bolo odovzdane priamo
