### ISSUE TITLE
KP - popísať používateľské rozhranie

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#2]

**Comment by kubis-svorc** [comment]
V odesku 3.1.11 je doplnené info. Prosím skontrolovať.

**Comment by pavelpetrovic** [comment]
este maly komentarik do tohto issue: ked cez issue oslovujete anonyma, ze ma nieco skontrolovat, tak 4 ludia, ktorym to pride si nemusia nutne vsetci pamatat (alebo vobec vediet) koho tym myslite, piste sem, prosim, vzdy adresne koho prosite o prislusnu akciu. dakujem. :)
