### ISSUE TITLE
Navrh (C) 

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#20]
návrh používateľského rozhrania (GUI)

**Comment by keszeghova** [comment]
upravit 1 verziu GUI - kazde okno aplikacie na samostatny obrazok s popisom a nadpismi, zvacsit font

**Comment by Anna-Rebeka** [comment]
všetky GUI pripomienky som zapracovala, čakám na schválenie či to môže byť OK

**Comment by Anna-Rebeka** [comment]
GUI bolo schválené všetkými stakeholdermi
