### ISSUE TITLE
doriesit komunikaciu so zadavatelom 

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#25]
ci merat aj napatie,
informacie o pristroji,
ako sa vedia ziaci orientovat vo vacsich grafoch a tabulkach

**Comment by kubis-svorc** [comment]
Niekoľko krát som kontaktoval zadávatelku, avšak zatiaľ bez odozvy. 
Na prvom stretnutí spomínala, že majú problémy s emailovou schránkou. 
Kontaktoval som ju aj cez SMS, takže zatiaľ čakám na odpoveď.

**Comment by kubis-svorc** [comment]
Keďže ich mailová schránka nefunguje, posiela súkromný mail: zdevitalisova@gmail.com
