### ISSUE TITLE
Ovládanie aplikácie

### ISSUE THREAD

**Issue by kubis-svorc** [TIS2019-FMFI/meranie-velicin#30]

**Comment by kubis-svorc** [comment]
Ovládanie aplikácie bude iba pomocou klávesnice. Niektoré okná s možnosťami nastavovania budú vyskakovať až po odkliknutí tlačidla ENTER. 
V tabuľke sa bude skrolovať šípkami vľavo a vpravo. 
Posúvať medzi tlačidlami a oknami bude možné pomocou tabulátora a v prípade rolovacie okna s možnosťami šípkami. 
Myš bude možné používať takým spôsobom, že program NVDA bude čítať, načo myš nadíde. Teda bude možné používať aj myš.

**Comment by pavelpetrovic** [comment]
čo robia šípky vľavo a vpravo v tabuľke? posúvajú kurzor, alebo celú tabuľku?
posúvajú tabuľku vždy, alebo iba keď tabuľka dostane tabulátorový focus?
ako to bude s posúvaním grafu?
skúste tú spoluprácu NVDA preskúmať na nejakom testovacom príklade čo najskôr, aby ste to vedeli uzavrieť.

**Comment by kubis-svorc** [comment]
Šípkami v tabulke sa bude pohybovať po okienkach tabulky, po tom, ako dostane tabulátorový focus.
Graf bude statickej veľkosti a pri väčšom množstve záznamov sa graf zhustí.

**Comment by Anna-Rebeka** [comment]
Do ovládania aplikácie sa pridali klávesové skratky pre tlačidlá.
Všetky budú uvedené v návrhu.
