### ISSUE TITLE
KP - zmena

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#31]
Zmena v ovladani - meranie si ukonci ziak sam (nebude sa zadavat doba merania)
postupne ako sa zaznamenavaju hodnoty v jednotlivych casovych intevarloch (napr.kazdych 10s) tak ich aplikacia precita a zapise do tabulky (citanie je potrebne na to aby ziak vedel kedy ma meranie zastavit)

**Comment by pavelpetrovic** [comment]
s tym citanim to upresnite, lebo asi nebude citat vsetky namerane hodnoty
