### ISSUE TITLE
KP - najnovsia verzia 31.10.2019

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#35]
Bola nahrata najnovisa verzia. 
Po stretnuti so zadavatelom pri zapozicavani multimetra doslo k zmene ovladania. Ziaci nebudu nastavovat dobu merania, ale v istych casovych intervaloch sa im budu namerane hodnoty zaznemanavat v aplikacii. Citanie hodnot je potrebne na to aby ziak vedel kedy ma meranie ukoncit.

Nastavenia portu budu popisane v navrhu v casti A.

**Comment by pavelpetrovic** [comment]
dakujem za aktualizovany KP.

3.1.4. mi pripada ako nerealizovatelna poziadavka, ak nastavim periodu 1s, asi nie je mozne hodnotu celu odrozpravat za 1s... patrilo by sa tam vysvetlit, co to bude robit v takom pripade.

3.1.9.4 nebolo by praktickejsie po odstartovani merania zablokovat vsetky ostatne ovladacie prvky, okrem STOP?

chyba mi tam to nastavovanie portu, na ktore sa zariadenie pripaja, alebo autodetekcia, nestaci to presunut do navrhu, patri to do specifikacie - aspon ci sa to bude same vediet detekovat, alebo ci pouzivatel ma moznost port nastavit

**Comment by keszeghova** [comment]
Dobry den, objasnili sme ovladanie aplikacie a nastavovanie meranej veliciny. Taktiez sme zmenili minimalnu periodu na 5s aby sa namerane hodnoty dali citat. Doplnili sme aj informacie o nastaveni portu.

**Comment by pavelpetrovic** [comment]
tu by som sa ale radsej prihovoril, aby ostala 1s perioda s tym, ze sa jednoducho neprecita kazda namerana hodnota ale iba tak casto, ako to stihne rozpravat.
ak sa pouziva externa citacka, tak sice neviem, co to znamena, ale Vy to urcite zvladnete.
v pripade merania nejakych javov je aj sekunda prilis dlha doba, ale nech, ale dlhsie ako sekunda mi uz pripada skoro nepouzitelne...
