### ISSUE TITLE
KP - verzia 4.11.2019 #35 

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#37]

**Comment by pavelpetrovic** [comment]
dakujem. az na tych 5s, ako som pisal, to akceptujem. tych 5s, prosim, este zvazte.
vysledok potom poslite zadavatelke, aby si ho dokladne prestudovala a dala Vam k tomu spatnu vazbu, cokolvek, co sa jej nezda, lebo podla tohto to naprogramujete, tiez si s nou dohodnite termin na stretnutie ohladne podrobneho prediskutovania pouzivatelskeho rozhrania (ked bude z vasej strany jeho navrh vo finalnej podobe).

**Comment by keszeghova** [comment]
KP bol schvaleny
