### ISSUE TITLE
KP - pridať informáciu o možnom rozšírení aplikácie

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#4]
softvér bude pripravený aj na pripojenie špecializovaného zariadenia, ktoré dodá cvičiaci, na čítanie grafov ...

**Comment by Anna-Rebeka** [comment]
doplnené ako bod 3.4. - Možné rozšírenie aplikácie
prosím skontrolovať :)

**Comment by keszeghova** [comment]
je to tam :))
