### ISSUE TITLE
Prekonzulovat navrh GUI so zadavatelkou

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#43]

**Comment by Anna-Rebeka** [comment]
Stretli sme sa. So všetkým súhlasila.
Pozn. : Farebné prevedenie GUI v súbore NÁVRH nebude finálnym farebným prevedením aplikácie - to bude v zhode s KP. 
Farebné prevedenie v súbore NÁVRH je z čisto estetických dôvodov a našej voľby internetového nástroju https://proto.io/ pre tvorbu návrhu GUI.

**Comment by keszeghova** [comment]
Navrh GUI bol skonzultovany.
