### ISSUE TITLE
Ziskat oficialny suhlas od zadavatelky (na KP)

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#44]

**Comment by kubis-svorc** [comment]
Poslal som jej najnovšiu verziu KP s tým, aby si to pozorne prečítala a v prípade, že nebude mať ďalšie pripomienky nám to oficiálne odsúhlasila.
Čakáme na vyjadrenie

**Comment by kubis-svorc** [comment]
Stále čakám.

**Comment by keszeghova** [comment]
Oficialny suhlas bol poslany.
