### ISSUE TITLE
KP - upraviť/doplniť odsek 3.1.8 o ukladaní meraní

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#7]

**Comment by keszeghova** [comment]
malo by to tam byt, mozete to skontrolovat niekto

**Comment by kubis-svorc** [comment]
Skontroloval som. Nebolo by lepšie napísať, že nastavenie sa uloží ako že si ho program zapamätá?

**Comment by keszeghova** [comment]
prepisala som to na ulozi
