### ISSUE TITLE
citanie nameranej hodnoty v pripade nizkeho intervalu merania

### ISSUE THREAD

**Issue by keszeghova** [TIS2019-FMFI/meranie-velicin#77]

**Comment by keszeghova** [comment]
citanie aktualne nemarenej hodnoty (ta co sa pridava do tabulky funguje)
zopakovanie naposledy precitanej je pripravene staci nabindovat CTRL+R s read_last medotou v triede table.py

**Comment by Savlar** [comment]
citanie funguje len pre prvu pridanu hodnotu a potom az na 13. a dalsie, je zrejme problem v posuvani sa po poliach tabulky

**Comment by Savlar** [comment]
este je problem s citanim pokial je interval merania male cislo, neprecita sa cela hodnota

**Comment by Savlar** [comment]
pri vytvoreni exe cez pyinstaller nefunguje citanie vobec

**Comment by keszeghova** [comment]
ten maly interval by sa dal vyriesit tak ze by sa citala kazda 2ha pripadne 3tia hodnota (podla intervalu aky je)

**Comment by pavelpetrovic** [comment]
neviem, ci rozumiem problemu, ale mam pocit, ze z fyzikalneho hladiska by bolo korektne vsetky hodnoty, ktore pridu pocas periody jedneho vystupu, priemerovat.

**Comment by pavelpetrovic** [comment]
a pokial je frekvencia vystupu vacsia ako frekvencia vstupu, tak by podla mna aplikacia mala odmietnut nastavit taku vysoku frekvenciu (ak by ste totiz kopirovali poslednu platnu hodnotu, tak to korektne priemerovanie prestane fungovat).

inymi slovami, predstavte si, ze by niekto pocital integral zo vsetkych nameranych hodnot, ktore da vas vystup, mala by mu vyjst hodnota, ktora je blizka skutocnosti.  pri poruseni uvedenych 2 principov hrozi, ze to nebude sediet.

**Comment by Anna-Rebeka** [comment]
@pavelpetrovic tu ide konkrétne o čítanie nahlas hodnôt v tabuľke (nie o zaznamenanie hodnoty v prístroji),
lebo ak je perióda merania napríklad 1 sekunda, tak sa potom prečítanie hodnoty nestíha. (nová hodnota je zaznamenaná skôr než sa stihne vysloviť nahlas aktuálna resp. minulá hodnota teda napríklad vyslovenie čísla "dvadsať-štyri" trvá dlhšie než 1 sekundu)

**Comment by pavelpetrovic** [comment]
uz rozumiem, dakujem. tak potom to je jasne, ze nemoze rozpravat castejsie ako to stihne. 
bude treba nejaky odhad ako dlho mu trva vyslovit citanu hodnotu.

**Comment by Anna-Rebeka** [comment]
Bolo vyriešené v pull request #104
