### ISSUE TITLE
Table scroll

### ISSUE THREAD

**Issue by Savlar** [TIS2019-FMFI/meranie-velicin#85]
tabulka sa uz da scrollovat ked je v nej dostatocny pocet hodnot, je ale problem ked zacne pouzivatel scrollovat pocas merania, program sa zasekne a aplikacia po case spadne
#81

**Comment by Savlar** [comment]
zrejme to nebude mat jednoduchy fix, takze staci zakazat používateľovi scrollovat tabulku pocas merania

**Comment by Anna-Rebeka** [comment]
dočítala som sa  - "So there really isn't
any way to disable the scrollbars, other than making the window large
enough that they are not needed."

Neviem teda ako to vyriešiť..  ale koniec koncov oni ani nepoužívajú myš teda scrollovanie tabuľky spočíva iba v stláčaní šípiek a TABu na klávesnici - toto asi vieme bindnut, prepísať a tak zakázať. Či mal si niečo iné na mysli?

**Comment by Savlar** [comment]
ja by som to potom dal tak aby sa prepinalo medzi buttonmi a tabulkou TABom, ale po bunkach v tabulke by sa hybali sipkami pricom pocas merania by to bolo zakazane

**Comment by Savlar** [comment]
`wx.grid.Grid().ShowScrollbars(horizontal, vertical)`, kde parametre su `wx.SHOW_SB_NEVER` / `wx.SHOW_SB_ALWAYS`, uz som to zmenil v implementation
