### ISSUE TITLE
skalovanie buniek tabulky

### ISSUE THREAD

**Issue by Savlar** [TIS2019-FMFI/meranie-velicin#88]
v pripade ze pride do tabulky vysoka hodnota bude treba velkosti buniek vhodne naskalovat

**Comment by keszeghova** [comment]
#99

**Comment by pavelpetrovic** [comment]
pripominam, ze dohodnuty rezim prace je, ze ked niekto nieco ide naimplementovat, tak si vytvori z mastera novy branch, ked je hotovy, tak spravi pull request a mergene to do mastera, nasledne sa prislusny branch zmaze. zda sa, ze tento pattern nam v tomto projekte nejak usiel. :)
