### ISSUE TITLE
sposob instalacie driveru

### ISSUE THREAD

**Issue by Savlar** [TIS2019-FMFI/meranie-velicin#92]
v pripade ze sa nepodari vytvorit spojenie s pristrojom automaticky tak by mozno bolo dobre opytat sa pouzivatela ci chce nainstalovat driver, aby im zbytocne nevyskakovali nove okna + v skole nemozu instalovat sami
alebo poprosim nejake nazory ze ako by sme to mohli spravit aby to fungovalo vo vsetkych pripadoch

**Comment by kubis-svorc** [comment]
Bude mať zmysel pýtať sa či si to chcú nainštalovať aj keď nebudú mať na to niektorí oprávnenie?

**Comment by pavelpetrovic** [comment]
moj nazor je, ze by som instalaciu oddelil.
nech si to najskor nainstaluju podla navodu (alebo administrator)
a pocas pouzivania aplikacie sa uz predpoklada, ze je to nainstalovane, ak nie, tak aplikacia oznami, ze si to maju nainstalovat podla navodu.
