### ISSUE TITLE
nahradenie čítania tabulky textfieldami?

### ISSUE THREAD

**Issue by kubis-svorc** [TIS2019-FMFI/meranie-velicin#93]
Aby sme nezabudli - treba nejako nahradiť čítanie tabulky.

**Comment by Anna-Rebeka** [comment]
ale uvidí sa, podľa toho čo nám odpíše zadávateľka - ak budú mať dostupný internet, tak to nebude nutné 👍

**Comment by Anna-Rebeka** [comment]
Ukázalo sa, že nie je treba, zadávateľka odpísala, že budú mať dostupný internet.
