### ISSUE TITLE
scrollovanie tabulky

### ISSUE THREAD

**Issue by Savlar** [TIS2019-FMFI/meranie-velicin#97]
treba vymysliet novy sposob scrollovania tabulky automaticky pocas merania
- aktualny sposob posuvania sa po bunkach nie je vhodny pocas merania

**Comment by Anna-Rebeka** [comment]
myslím, že dnes sa to už vyrriešilo.
tu v #99  už je to OK.
tabuľka sa postupne posúva s prichádzajúcou hodnotou 👍 

...(Ich zaujíma len posledná hodnota, minimálne podľa toho čo hovorila zadávateľka. Teda až neskôr sa budú posúvať po celej tabuľke. Ďalšie iné hodnoty by sa ani nestíhali nahlas čítať..)
